# Based on https://www.gitpod.io/blog/gitpodify/
github:
  prebuilds:
    master: true
tasks:
  - init: cd app && yarn install --frozen-lockfile && yarn run cypress install
image:
  file: .gitpod.Dockerfile
ports:
  - port: 3000
    onOpen: open-browser
  - port: 3001
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
  - port: 3000-50000
    onOpen: ignore
